import type { CategoryId } from "@/types/metrics";
import type { TrendPolarity } from "@/lib/metric-config";

export interface MetricRegistryEntry {
  id: string;
  translationKey: string;
  fallbackLabel: string;
  unitKey: string;
  fallbackUnit: string;
  polarity: TrendPolarity;
  category: CategoryId;
  sourceField: string;
  previousPeriodField?: string;
  sourceName: string;
  /** Only show if value > 0 (skip zeros from data refresh gaps) */
  skipZero?: boolean;
  /** Extra props to merge into MetricCardProps */
  extra?: (value: number) => Record<string, unknown>;
}

/**
 * Every metric in one place. The hook loops over this instead of
 * having 30+ individual add() calls.
 */
export const METRIC_REGISTRY: MetricRegistryEntry[] = [
  // --- Community ---
  {
    id: "total_properties",
    translationKey: "totalProperties",
    fallbackLabel: "Total Properties",
    unitKey: "parcels",
    fallbackUnit: "parcels",
    polarity: "higher_is_better",
    category: "community",
    sourceField: "totalProperties",
    previousPeriodField: "totalProperties",
    sourceName: "MPROP (spatial)",
  },
  {
    id: "owner_occupied_rate",
    translationKey: "ownerOccupiedRate",
    fallbackLabel: "Owner-Occupied Rate",
    unitKey: "percent",
    fallbackUnit: "%",
    polarity: "higher_is_better",
    category: "community",
    sourceField: "ownerOccupiedRate",
    previousPeriodField: "ownerOccupiedRate",
    sourceName: "MPROP (spatial)",
  },
  {
    id: "avg_assessed_value",
    translationKey: "avgAssessedValue",
    fallbackLabel: "Avg Assessed Value",
    unitKey: "dollars",
    fallbackUnit: "per parcel",
    polarity: "higher_is_better",
    category: "community",
    sourceField: "avgAssessedValue",
    previousPeriodField: "avgAssessedValue",
    sourceName: "MPROP (spatial)",
  },
  {
    id: "population",
    translationKey: "population",
    fallbackLabel: "Population",
    unitKey: "residents",
    fallbackUnit: "residents",
    polarity: "higher_is_better",
    category: "community",
    sourceField: "population",
    previousPeriodField: "population",
    sourceName: "Census ACS",
  },
  {
    id: "median_income",
    translationKey: "medianIncome",
    fallbackLabel: "Median Household Income",
    unitKey: "dollars",
    fallbackUnit: "per year",
    polarity: "higher_is_better",
    category: "community",
    sourceField: "medianIncome",
    previousPeriodField: "medianIncome",
    sourceName: "Census ACS",
  },
  {
    id: "libraries",
    translationKey: "libraries",
    fallbackLabel: "Libraries",
    unitKey: "locations",
    fallbackUnit: "locations",
    polarity: "higher_is_better",
    category: "community",
    sourceField: "libraryCount",
    previousPeriodField: "libraryCount",
    sourceName: "MPL ArcGIS",
  },
  {
    id: "schools",
    translationKey: "schools",
    fallbackLabel: "Schools",
    unitKey: "schools",
    fallbackUnit: "schools",
    polarity: "higher_is_better",
    category: "community",
    sourceField: "schoolCount",
    previousPeriodField: "schoolCount",
    sourceName: "MPROP Layer 18",
  },
  {
    id: "parks",
    translationKey: "parks",
    fallbackLabel: "Parks",
    unitKey: "parks",
    fallbackUnit: "parks",
    polarity: "higher_is_better",
    category: "community",
    sourceField: "parkCount",
    previousPeriodField: "parkCount",
    sourceName: "MPROP Layer 16",
  },
  {
    id: "daycares",
    translationKey: "daycares",
    fallbackLabel: "Daycare Centers",
    unitKey: "centers",
    fallbackUnit: "centers",
    polarity: "higher_is_better",
    category: "community",
    sourceField: "daycareCount",
    sourceName: "MPROP Layer 19",
  },

  // --- Public Safety ---
  {
    id: "crime_total",
    translationKey: "totalCrimes",
    fallbackLabel: "Total Crimes",
    unitKey: "incidents",
    fallbackUnit: "incidents",
    polarity: "lower_is_better",
    category: "publicSafety",
    sourceField: "__crimeTotal", // special handling in hook
    previousPeriodField: "crimeTotal",
    sourceName: "WIBR Crime CSV (daily)",
  },
  {
    id: "crime_violent",
    translationKey: "violentCrimes",
    fallbackLabel: "Violent Crimes",
    unitKey: "incidents",
    fallbackUnit: "incidents",
    polarity: "lower_is_better",
    category: "publicSafety",
    sourceField: "crimeViolent",
    previousPeriodField: "crimeViolent",
    sourceName: "WIBR Crime CSV",
  },
  {
    id: "crime_property",
    translationKey: "propertyCrimes",
    fallbackLabel: "Property Crimes",
    unitKey: "incidents",
    fallbackUnit: "incidents",
    polarity: "lower_is_better",
    category: "publicSafety",
    sourceField: "crimeProperty",
    sourceName: "WIBR Crime CSV",
  },
  {
    id: "overdose_calls",
    translationKey: "overdoseCalls",
    fallbackLabel: "Overdose Calls",
    unitKey: "calls",
    fallbackUnit: "calls",
    polarity: "lower_is_better",
    category: "publicSafety",
    sourceField: "overdoseCount",
    skipZero: true,
    sourceName: "EMS Calls CSV",
  },
  {
    id: "traffic_crashes",
    translationKey: "trafficCrashes",
    fallbackLabel: "Traffic Crashes",
    unitKey: "incidents",
    fallbackUnit: "crashes",
    polarity: "lower_is_better",
    category: "publicSafety",
    sourceField: "trafficCrashCount",
    skipZero: true,
    sourceName: "Traffic Crash CSV",
  },
  {
    id: "fire_incidents",
    translationKey: "fireIncidents",
    fallbackLabel: "Fire Incidents",
    unitKey: "incidents",
    fallbackUnit: "incidents",
    polarity: "lower_is_better",
    category: "publicSafety",
    sourceField: "fireIncidentCount",
    sourceName: "MFD Dispatch",
  },
  {
    id: "police_stations",
    translationKey: "policeStations",
    fallbackLabel: "Police Stations",
    unitKey: "stations",
    fallbackUnit: "stations",
    polarity: "higher_is_better",
    category: "publicSafety",
    sourceField: "policeStationCount",
    sourceName: "MPD ArcGIS",
  },
  {
    id: "firehouses",
    translationKey: "firehouses",
    fallbackLabel: "Firehouses",
    unitKey: "stations",
    fallbackUnit: "stations",
    polarity: "higher_is_better",
    category: "publicSafety",
    sourceField: "firehouseCount",
    sourceName: "MFD ArcGIS",
  },

  // --- Quality of Life ---
  {
    id: "vacant_buildings",
    translationKey: "vacantBuildings",
    fallbackLabel: "Vacant Buildings",
    unitKey: "buildings",
    fallbackUnit: "buildings",
    polarity: "lower_is_better",
    category: "qualityOfLife",
    sourceField: "vacantBuildingCount",
    previousPeriodField: "vacantBuildingCount",
    sourceName: "Accela Vacant Buildings",
  },
  {
    id: "vacant_land",
    translationKey: "vacantLand",
    fallbackLabel: "Vacant Land",
    unitKey: "parcels",
    fallbackUnit: "parcels",
    polarity: "lower_is_better",
    category: "qualityOfLife",
    sourceField: "vacantLandCount",
    skipZero: true,
    sourceName: "MPROP (spatial)",
  },
  {
    id: "foreclosures_city",
    translationKey: "foreclosuresCity",
    fallbackLabel: "Foreclosures (City)",
    unitKey: "parcels",
    fallbackUnit: "parcels",
    polarity: "lower_is_better",
    category: "qualityOfLife",
    sourceField: "foreclosureCityCount",
    previousPeriodField: "foreclosureCityCount",
    sourceName: "Foreclosed Properties",
  },
  {
    id: "foreclosures_bank",
    translationKey: "foreclosuresBank",
    fallbackLabel: "Foreclosures (Bank)",
    unitKey: "parcels",
    fallbackUnit: "parcels",
    polarity: "lower_is_better",
    category: "qualityOfLife",
    sourceField: "foreclosureBankCount",
    previousPeriodField: "foreclosureBankCount",
    sourceName: "Foreclosed Properties",
  },
  {
    id: "service_requests_311",
    translationKey: "serviceRequests311",
    fallbackLabel: "311 Service Requests",
    unitKey: "requests",
    fallbackUnit: "requests",
    polarity: "lower_is_better",
    category: "qualityOfLife",
    sourceField: "serviceRequests311",
    previousPeriodField: "serviceRequests311",
    sourceName: "311 Call Center CSV",
  },
  {
    id: "resolution_rate",
    translationKey: "resolutionRate",
    fallbackLabel: "311 Resolution Rate",
    unitKey: "percent",
    fallbackUnit: "%",
    polarity: "higher_is_better",
    category: "qualityOfLife",
    sourceField: "serviceRequestsResolutionRate",
    sourceName: "311 Call Center CSV",
  },
  {
    id: "avg_resolution_days",
    translationKey: "avgResolutionDays",
    fallbackLabel: "Avg Resolution Time",
    unitKey: "days",
    fallbackUnit: "days",
    polarity: "lower_is_better",
    category: "qualityOfLife",
    sourceField: "serviceRequestsAvgDays",
    sourceName: "311 Call Center CSV",
  },
  {
    id: "building_permits",
    translationKey: "buildingPermits",
    fallbackLabel: "Building Permits",
    unitKey: "permits",
    fallbackUnit: "permits",
    polarity: "higher_is_better",
    category: "qualityOfLife",
    sourceField: "buildingPermitCount",
    skipZero: true,
    sourceName: "Building Permits CSV",
  },

  // --- Development ---
  {
    id: "property_sales",
    translationKey: "propertySales",
    fallbackLabel: "Property Sales (2024)",
    unitKey: "sales",
    fallbackUnit: "sales",
    polarity: "higher_is_better",
    category: "development",
    sourceField: "propertySalesCount",
    previousPeriodField: "propertySalesCount",
    skipZero: true,
    sourceName: "Property Sales CKAN",
  },
  {
    id: "median_sale_price",
    translationKey: "medianSalePrice",
    fallbackLabel: "Median Sale Price",
    unitKey: "dollars",
    fallbackUnit: "dollars",
    polarity: "higher_is_better",
    category: "development",
    sourceField: "medianSalePrice",
    previousPeriodField: "medianSalePrice",
    sourceName: "Property Sales CKAN",
  },
  {
    id: "liquor_licenses",
    translationKey: "liquorLicenses",
    fallbackLabel: "Liquor Licenses",
    unitKey: "licenses",
    fallbackUnit: "licenses",
    polarity: "higher_is_better",
    category: "development",
    sourceField: "liquorLicenseCount",
    skipZero: true,
    sourceName: "Liquor Licenses CKAN",
  },
  {
    id: "total_permit_investment",
    translationKey: "totalPermitInvestment",
    fallbackLabel: "Total Permit Investment",
    unitKey: "dollars",
    fallbackUnit: "dollars",
    polarity: "higher_is_better",
    category: "development",
    sourceField: "totalPermitInvestment",
    previousPeriodField: "totalPermitInvestment",
    sourceName: "Building Permits CSV",
  },
  {
    id: "new_construction",
    translationKey: "newConstruction",
    fallbackLabel: "New Construction",
    unitKey: "permits",
    fallbackUnit: "permits",
    polarity: "higher_is_better",
    category: "development",
    sourceField: "newConstructionCount",
    skipZero: true,
    sourceName: "Building Permits CSV",
  },

  // --- Wellness ---
  {
    id: "poverty_rate",
    translationKey: "povertyRate",
    fallbackLabel: "Poverty Rate",
    unitKey: "percent",
    fallbackUnit: "%",
    polarity: "lower_is_better",
    category: "wellness",
    sourceField: "povertyRate",
    previousPeriodField: "povertyRate",
    sourceName: "Census ACS",
  },
  {
    id: "unemployment",
    translationKey: "unemployment",
    fallbackLabel: "Unemployment Rate",
    unitKey: "percent",
    fallbackUnit: "%",
    polarity: "lower_is_better",
    category: "wellness",
    sourceField: "unemploymentRate",
    previousPeriodField: "unemploymentRate",
    sourceName: "Census ACS",
  },
  {
    id: "median_home_value",
    translationKey: "medianHomeValue",
    fallbackLabel: "Median Home Value",
    unitKey: "dollars",
    fallbackUnit: "dollars",
    polarity: "higher_is_better",
    category: "wellness",
    sourceField: "medianHomeValue",
    sourceName: "Census ACS",
  },
  {
    id: "food_inspection",
    translationKey: "foodInspectionPassRate",
    fallbackLabel: "Food Inspection Pass Rate",
    unitKey: "percent",
    fallbackUnit: "%",
    polarity: "higher_is_better",
    category: "wellness",
    sourceField: "foodInspectionPassRate",
    sourceName: "Open Data Portal",
    extra: (value: number) => ({
      progress: { value, label: "passing" },
    }),
  },
];
